numberOfVacantRooms: 0
roomTypeText: economy
chatGroupName: test
messageIdentifier: NEW DELAYED
messageCheckIntervalMs: 100
responseText: HIL CAN
responseLimit: 3
responseWindowMinutes: 10
isOptimistic: true
inputSelectorElement: div._ak1r
allowPartialFulfilment: true
